baseURL: https://ziyuechen2021.netlify.app/
languageCode: en-us
title: Portfolio website for Ziyue Chen
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      
    title: Hi, my name is Ziyue Chen
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: zchen.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: sep.jpg
        subtitle: TNT
        title: Ziyue
        url: blogs/ziyuechen
      - image: pic02.jpg
        subtitle: HOMEWORKONE
        title: HOMEWORK01
        url: blogs/HOMEWORK
      - image: pic03.jpg
        subtitle: SessioneOne
        title: HOMEWORK
        url: blogs/magna
      - image: pic04.jpg
        subtitle: IMDBdataset
        title: Analysisofmovies
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Born in China."
    title: Homeland
    url: blogs
